name: link_note
description: "Share and sync text easily between your devices using QR codes or clipboard.."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^7.1.2
  path: ^1.9.1
  pretty_qr_code: ^3.5.0
  scanner_overlay: ^0.0.2
  supabase_flutter: ^2.10.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  rename: ^3.1.0
  msix: ^3.16.12

flutter:
  uses-material-design: true

msix_config:
  display_name: Link Note
  publisher_display_name: Bofaisal
  identity_name: www.bhf.com
  msix_version: 1.0.0.0
  logo_path: E:\Projects\Link Note\link_note\assets\images\app_logo.png